name: trypanophobe

services:
  filter:
    build:
      context: .
      dockerfile: docker/Dockerfile
      secrets:
        - hf_token
    image: trypanophobe
    ports:
      - "${SMOKE_PORT:-8080}:8080"
    deploy:
      resources:
        limits:
          cpus: "7.0"
          memory: 10G
        reservations:
          cpus: "2.0"
          memory: 6G

secrets:
  hf_token:
    environment: HF_TOKEN
