[supervisord]
nodaemon=true
user=root
logfile=/dev/fd/1
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:pihole]
user=pihole
command=/usr/bin/pihole-FTL -f
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ocr]
command=/root/.local/bin/uv run --directory /opt/trypanophobe/ocr python server.py
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:chunker]
command=/root/.local/bin/uv run --directory /opt/trypanophobe/chunker python server.py
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:trypanophobe]
command=/usr/local/bin/trypanophobe
autostart=true
autorestart=true
priority=40
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
